#!/usr/bin/env bash
# Starting anew ubuntu
#

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start a  nginx service
sudo service nginx start

# Allow the nginx to be on fire wall
sudo ufw allow 'Nginx HTTP'

# Ggiving website files ownership to user
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Bback up a default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Ccreat a  new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Rrestart the  nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
