#!/usr/bin/env bash

# update

apt-get update

# Install nginx

apt-get install -y nginx


# create nignx/html

mkdir /etc/nginx/html

#  Create a html file

touch /etc/nginx/html/index.html

# write hello world to index file

echo "Hello World!" > /etc/nginx/html/index.html

# niginx set

printf %s "server {

     listen      80;

     listen      [::]:80 default_server;

     root        /etc/nginx/html;

     index       index.html index.htm;

}

" > /etc/nginx/sites-available/default


# rrestart

service nginx restart
