#!/usr/bin/env bash
# n
# 0
# g
#


echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# nigmx
sudo service nginx start

# nginx 
sudo ufw allow 'Nginx HTTP'

# nginx 
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# nginc
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# nginex
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# nginx
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
