#!/usr/bin/env bash
# Doubles webservers

# make a new nginx
apt-get  update ; apt-get -y install nginx

string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf
# Restarting the nginx
sudo service nginx restart
