#!/usr/bin/env bash
# automaoton config
sudo apt-get -y update
sudo apt-get -y install nginx
sed -i "/server_name _;/ a\\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default
sudo service nginx restart
