#!/usr/bin/env bash
# config haproxy LB

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6 
apt-get install haproxy=2.6.\*
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 515407-web-01 100.25.117.246
        server 515407-web-02 54.237.34.73" >> /etc/haproxy/haproxy.cfg

service haproxy restart
