#!/usr/bin/env bash
# Config a HAporxy on load balancer

apt-get update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.4
apt-get -y install haproxy

# config of the load balancer
DOMAIN_NAME='munyasi.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG=\
"
# domain_name-backend
backend $DOMAIN_NAME-backend
	balance roundrobin
    server 515407-web-01 34.229.69.160 check
    server 515407-web-02 54.237.34.73 check

frontend $DOMAIN_NAME-frontend
	bind *:80
	mode http

	default_backend $DOMAIN_NAME-backend
#domain_name-backend-
"

[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < $CONFIG_FILE)

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
	sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
	echo 'ENABLED=1' >> $INIT_FILE
fi

if [ "$CONFIG_WORDS" -eq 0 ]; then
	echo -e "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
else
	start_tkn="#--$DOMAIN_NAME-params-begin--"
	end_tkn="#--$DOMAIN_NAME-params-end--"
	a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
	b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
	a=$((a - 1))
	b=$((b + 1))
	sed -i "$a,$b"d "$CONFIG_FILE"
	echo -en "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
fi

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	service haproxy start
else
	service haproxy restart
fi
