#!/usr/bin/env bash
#fizzbuzz
for n in {1..100}
do
  if (( n % 3 == 0 && n % 5 == 0))
  then
    echo "FizzBuzz"
  elif (( n % 5 == 0))
  then
    echo "Buzz"
  elif (( n % 3 == 0))
  then
    echo "Fizz"
  else
    echo "$n"
  fi
done
