#!/usr/bin/env bash
#display bad luck for 4th loop and good for 8th loop and best school for others
n=0
while [ $n -lt 10 ]
do
if [$n -eq 3 ]
then
echo "bad luck"
elif [ $n -eq 7 ]
then
echo "good luck"
else
echo "Best School"
fi
((n++))
done
