#!/usr/bin/env bash
# ssh client

Host *
   PasswordAuthentication no
   IdentityFile ~/.ssh/school
   SendEnv LANG LC_*
   HashKnownHosta yes
   GSSAPIAuthentication yes
   GSSAPIDelegateCredentials no
